<?php 
$videojuegos = array(
	array("nombre" => "Animal Crossing: New Horizons", "creador" => "Nintendo", "anio" => 2020),
	array("nombre" => "Assassin's Creed", "fecha" => "2007-11-13", "creador" => "Patrice Désilets"),
	array("nombre" => "BioShock", "fecha" => "2007-08-21", "creador" => "Ken Levine"),
	array("nombre" => "Call of Duty", "fecha" => "2003-10-29", "creador" => "Infinity Ward"),
	array("nombre" => "Dark Souls", "fecha" => "2011-09-22", "creador" => "Hidetaka Miyazaki"),
	array("nombre" => "Elder Scrolls V: Skyrim", "fecha" => "2011-11-11", "creador" => "Todd Howard"),
	array("nombre" => "Fallout 4", "fecha" => "2015-11-10", "creador" => "Todd Howard"),
	array("nombre" => "Grand Theft Auto V", "fecha" => "2013-09-17", "creador" => "Rockstar North"),
	array("nombre" => "Halo: Combat Evolved", "fecha" => "2001-11-15", "creador" => "Bungie"),
	array("nombre" => "Mario Kart 8 Deluxe", "creador" => "Nintendo", "anio" => 2017),
	array("nombre" => "Mario Party Superstars", "creador" => "Nintendo", "anio" => 2021),
	array("nombre" => "Metroid Dread", "creador" => "Nintendo", "anio" => 2021),
	array("nombre" => "Minecraft", "fecha" => "2011-11-18", "creador" => "Markus Persson"),
	array("nombre" => "Pokemon Sword and Shield", "creador" => "Nintendo", "anio" => 2019),
	array("nombre" => "Pokémon Brilliant Diamond and Shining Pearl", "creador" => "Nintendo", "anio" => 2021),
	array("nombre" => "Portal", "fecha" => "2007-10-09", "creador" => "Valve Corporation"),
	array("nombre" => "Splatoon 2", "creador" => "Nintendo", "anio" => 2017),
	array("nombre" => "Super Mario 3D World + Bowser's Fury", "creador" => "Nintendo", "anio" => 2021),
	array("nombre" => "Super Mario Odyssey", "creador" => "Nintendo", "anio" => 2017),
	array("nombre" => "Super Smash Bros. Ultimate", "creador" => "Nintendo", "anio" => 2018),
	array("nombre" => "The Legend of Zelda: Breath of the Wild", "creador" => "Nintendo", "anio" => 2017),
	array("nombre" => "The Legend of Zelda: Link's Awakening", "creador" => "Nintendo", "anio" => 2019),
	array("nombre" => "The Legend of Zelda: Skyward Sword HD", "creador" => "Nintendo", "anio" => 2021)
);